### ISSUE TITLE
Show Testbed Nodes in GeoRSS format

### ISSUE THREAD

**Issue by ichatz** [itm/uberdust#3]
When displaying the nodes of a testbed also to include a link that exports the nodes in GeoRSS feed format:

/uberdust/testbed/1/georss

title - Node urn
content - Node description, capabilities (as links)...

end result:

http://maps.google.com/maps?q=http://uberdust/georss

**Comment by whantana** [comment]
Also fix the point alignment on the map using stuff from WiseUI
