### ISSUE TITLE
Display Build number

### ISSUE THREAD

**Issue by ichatz** [itm/uberdust#31]
At the header of each page response, make sure that the project name "Uberdust" appears along with the version + build number provided by HUDSON.

http://stackoverflow.com/questions/7856682/attaching-build-number-for-binaries-in-maven

http://weblogs.java.net/blog/johnsmart/archive/2008/03/using_hudson_en.html

**Comment by whantana** [comment]
Reopened : use different approach. Place BUILD_NUMBER in property files and then as resource . more details on neda
