### ISSUE TITLE
Create Web-Socket Servlet server

### ISSUE THREAD

**Issue by ichatz** [itm/uberdust#35]

**Comment by whantana** [comment]
Websocket servers are now in place and injected in the Spring container of uberdust webapp. The current implementation is based on the Resin Web Server web sockects implementation. On the client side we need to make the websocket library we provide as generic as possible. Currently the websockets implementation we use on the reading providers are tied up to specific implementations and designs i.e the web socket client is forced to connect on disconnect or keep connection alive. Users of this library might not need this functionility and a custom implementation coded by them could be more approriate. Of course we could also provide default-like implementations based on the stuff we've already code.
