### ISSUE TITLE
Important PMD warning : J2EE & Thread spawning

### ISSUE THREAD

**Issue by whantana** [itm/uberdust#39]
After the introduction of the event listeners a serious in my opinion warning came up in the PMDs on thread spawning within J2EE apps

The PMD warning : http://ru1.cti.gr/hudson/job/wiseml/106/pmdResult/category.262987391/
Discussion : http://stackoverflow.com/questions/533783/why-spawning-threads-in-j2ee-container-is-discouraged

**Comment by akribopo** [comment]
The link is from the wiseml build. Wiseml is not a J2EE app. 

So the j2ee.xml ruleset should be removed from the maven-pmd-plugin on wiseml pom.xml.
